DESIGN_NAME: SHA256
VERILOG_FILES: dir::../../../references/CDragon-SHA-256/Verilog/SHA256.v
VERILOG_INCLUDE_DIRS:
  - dir::../../../references/CDragon-SHA-256/Verilog
USE_SLANG: true
CLOCK_PORT: clk
CLOCK_PERIOD: 20.0
FP_SIZING: relative
FP_CORE_UTIL: 20
PL_TARGET_DENSITY_PCT: 35
RUN_LINTER: true

pdk::sky130*:
  CLOCK_PERIOD: 15.0
  FP_CORE_UTIL: 20
  PL_TARGET_DENSITY_PCT: 35

pdk::gf180mcu*:
  CLOCK_PERIOD: 25.0
  FP_CORE_UTIL: 18
  PL_TARGET_DENSITY_PCT: 32
  MAX_FANOUT_CONSTRAINT: 4
