DESIGN_NAME: gcd
VERILOG_FILES: dir::rtl/gcd.v
USE_SLANG: true
CLOCK_PORT: clk
CLOCK_PERIOD: 20.0
FP_CORE_UTIL: 35
PL_TARGET_DENSITY_PCT: 45

pdk::sky130*:
  CLOCK_PERIOD: 15.0
  FP_CORE_UTIL: 40

pdk::gf180mcu*:
  CLOCK_PERIOD: 25.0
  FP_CORE_UTIL: 30
  PL_TARGET_DENSITY_PCT: 40
